from selenium.webdriver.common.by import By



class ShippingAdvice():
    
    
#     SA_button_element = [By.XPATH,'//div[contains(text(),"S/A登録")]/../div[0]']
    SA_button_element = [By.XPATH,'//*[@id="app"]/div[10]/main/div/div[1]/div/div[2]/div/div/div/div[2]/div[1]']
    newlyBuilt_element = [By.XPATH,'//a[@class="ml-2 v-btn v-btn--router theme--light"]']
    INV_add_element = [By.XPATH,'//*[@id="app"]/div[25]/main/div/div[1]/div[3]/div[2]/button[1]/div']
    IV_NO_element = [By.XPATH,'//input[@aria-label="I/V NO"]']
    search_element = [By.XPATH,'//*[@id="app"]/div[7]/div/div/div[2]/button[1]']
    choose_click_element = [By.XPATH,'//*[@id="app"]/div[7]/div/div/div[3]/div[1]/table/tbody/tr/td[1]/div/div/div/div/input']
    IV_list_add_element = [By.XPATH,'//*[@id="app"]/div[7]/div/div/div[2]/button[2]/div']
    Master_BL_NO_element = [By.XPATH,'//input[@aria-label="Master B/L NO"]']
    House_BL_NO_element = [By.XPATH,'//input[@aria-label="House B/L NO"]']
    trust_day_element = [By.XPATH,'//input[@aria-label="依頼日"]']
#     date_click_element = [By.XPATH,'//div[contains(text(),"24日")]/../button']
    trust_day_click_element = [By.XPATH,'//*[@id="app"]/div[1]/div/div[2]/div/div[2]/table/tbody/tr[4]/td[6]/button']
    issue_date_element = [By.XPATH,'//input[@aria-label="B/L発行日"]']
    issue_date_click_element = [By.XPATH,'//*[@id="app"]/div[1]/div/div[2]/div/div[2]/table/tbody/tr[5]/td[5]/button']
    loading_port_element = [By.XPATH,'//input[@aria-label="積出港"]']
    loading_port_choice_elements = [By.XPATH,'//*[@id="app"]/div[17]/div/div/div']
#     ETD_element = [By.XPATH,'//input[@aria-label="ETD"]']
    ETA_element = [By.XPATH,'//main/div/div[1]/div[2]/form/div/div/div[8]/div/div[1]/div/div/div[1]/div[1]/input']
    ETA_click_element = [By.XPATH,'//*[@id="app"]/div[1]/div/div[2]/div/div[2]/table/tbody/tr[5]/td[6]/button']
#     transport_form_element = [By.XPATH,'//input[@aria-label="輸送形態"]']
    loading_method_element = [By.XPATH,'//input[@aria-label="積み方"]']
    loading_method_choice_elements = [By.XPATH,'//*[@id="app"]/div[4]/div/div//a']
#     port_of_discharge = [By.XPATH,'//input[@aria-label="陸揚港"]']
#     currency_element = [By.XPATH,'//input[@aria-label="通貨"]']
    export_declaration_date_element = [By.XPATH,'//input[@aria-label="輸出通関日"]']
    export_declaration_date_click_element = [By.XPATH,'//*[@id="app"]/div[1]/div/div[2]/div/div[2]/table/tbody/tr[4]/td[7]/button']
    shipping_co_element = [By.XPATH,'//input[@aria-label="船社・航空会社"]']
    shipping_co_choice_element1 = [By.XPATH,'//*[@id="app"]/div[16]/div/div/div[1]/a']
    shipping_co_choice_element2 = [By.XPATH,'//*[@id="app"]/div[17]/div/div/div[1]/a']
    ships_name_element = [By.XPATH,'//main/div/div[1]/div[2]/form/div/div/div[15]/div/div/div[1]/div[1]/input']
    VOYAGE_NO_element = [By.XPATH,'//main/div/div[1]/div[2]/form/div/div/div[16]/div/div/div[1]/div[1]/input']
    SI_NO_element = [By.XPATH,'//input[@aria-label="S/I NO"]']
    customs_broker_element = [By.XPATH,'//input[@aria-label="通関業者"]']
    customs_broker_choice_element1 = [By.XPATH,'//*[@id="app"]/div[15]/div/div//a']
    customs_broker_choice_element2 = [By.XPATH,'//*[@id="app"]/div[16]/div/div//a']
    cargo_type_element = [By.XPATH,'//input[@aria-label="貨物タイプ"]']
    cargo_type_choice_element1 = [By.XPATH,'//*[@id="app"]/div[14]/div/div//a']
    cargo_type_choice_element2 = [By.XPATH,'//*[@id="app"]/div[15]/div/div//a']
    INV_checklist_element = [By.XPATH,'//main/div/div[1]/div[3]/div[3]/div/table/tbody/tr/td[1]/div/div/div/div/input']
    container_NO_element = [By.XPATH,'//main//table/tbody/tr/td[2]/div/div/div[1]/div/input']
    container_size_element = [By.XPATH,'//main//table/tbody/tr/td[3]/div/div/div[1]/div[1]/input']
    container_size_choice_element = [By.XPATH,'//*[@id="app"]/div[1]/div/div/div/a']
    PID_element = [By.XPATH,'//input[@placeholder="識別番号"]']
    temporary_saving_element = [By.XPATH,'//main/div/div[1]/div[1]/div[2]/button[1]']
    confirm_button_element = [By.XPATH,'//div[@class="v-dialog v-dialog--active"]//button']
    file_upload_element = [By.XPATH,'//main/div/div[1]/div[1]/div[2]/button[5]']
    upload_choice_element = [By.XPATH,'//div[@role="radiogroup"]//input']
    upload_button_element = [By.XPATH,'//div[@class="v-dialog v-dialog--active"]/div/div[3]/div/div/div/input']
    close_button_element = [By.XPATH,'//div[@class="v-dialog__content v-dialog__content--active"]/div/div/div[3]/button']
    sending_confirmation_element = [By.XPATH,'//main/div/div[1]/div[1]/div[2]/button[4]']
    sure_button_element = [By.XPATH,'//div[@class="v-dialog v-dialog--active"]//button[1]']
    